ALTER TABLE job_events ADD COLUMN IF NOT EXISTS from_status VARCHAR(40);
ALTER TABLE job_events ADD COLUMN IF NOT EXISTS to_status VARCHAR(40);
ALTER TABLE job_events ADD COLUMN IF NOT EXISTS worker_id VARCHAR(100);
